### ISSUE TITLE
Add Python 3 support.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [davidjamesca/ctypesgen#48] opened 2015-03-13 15:54 UTC
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `luoyongg...@gmail.com` on 31 Oct 2013 at 7:04

**Comment by davidjamesca** [comment] 2015-05-11 17:02
Duplicate of #51

**Closed** 2015-05-11 17:04 UTC
Labels: auto-migrated, duplicate, Priority-Medium, Type-Defect
